version: '3.8'

services:
  app-blue:
    build: .
    ports:
      - "3002:3000"
    environment:
      - NODE_ENV=production
      - DEPLOYMENT_COLOR=blue

  app-green:
    build: .
    ports:
      - "3003:3000"
    environment:
      - NODE_ENV=production
      - DEPLOYMENT_COLOR=green

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - type: bind
        source: ./nginx/nginx.conf
        target: /etc/nginx/nginx.conf
        read_only: true

  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    volumes:
      - type: bind
        source: ./prometheus
        target: /etc/prometheus
        read_only: true

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3001:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
    volumes:
      - type: bind
        source: ./grafana/provisioning
        target: /etc/grafana/provisioning
        read_only: true

  loki:
    image: grafana/loki:2.9.2
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml

  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - "16686:16686"
      - "14268:14268"

networks:
  default:
    driver: bridge
