global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'blue'
    static_configs:
      - targets: ['app-blue:3000']
    metrics_path: '/metrics'

  - job_name: 'green'
    static_configs:
      - targets: ['app-green:3000']
    metrics_path: '/metrics'

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
